server {
    listen 80;
    server_name localhost;

    # 1. Internal Docker DNS 
    resolver 127.0.0.11 valid=30s;

    # ---------------------------------------------------------
    # THE CENTRAL HUB
    # ---------------------------------------------------------
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ =404;
    }

    # ---------------------------------------------------------
    # PROYECTO: INVENTARIO IT (Frontend)
    # ---------------------------------------------------------
    location /inventario/ {
        set $upstream_inventario http://inventario-frontend:80;
        
        # When using variables, Nginx does not trim the URL automatically.
        # This line removes "/inventario" before passing it to your web app.
        rewrite ^/inventario/(.*) /$1 break;
        
        proxy_pass $upstream_inventario;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ---------------------------------------------------------
    # PROYECTO: INVENTARIO IT (Backend API)
    # ---------------------------------------------------------
    location /api/v1/ {
        set $upstream_backend http://inventario-backend:8080;
        
        proxy_pass $upstream_backend;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    
}